GET http://localhost:3000/api/v1/users

###

GET http://localhost:3000/api/v1/products

###

GET http://localhost:3000/api/v1/products?limit=4&offset=3

###

POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "name": "Zapatos 12",
  "price": 1212,
  "description": "New Shoes for you",
  "image": "http://placeimg.com/640/480",
  "categoryId": 3
}

###

POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "email": "Fernando33@gt.com",
  "password": "papapapapapa",
  "role": "owner"
}

###

GET http://localhost:3000/api/v1/users/4

###

PATCH http://localhost:3000/api/v1/users/4
Content-Type: application/json

{
  "email": "andrea2@alison.com"
}

###

DELETE http://localhost:3000/api/v1/users/1

###

GET http://localhost:3000/api/v1/customers

###

POST http://localhost:3000/api/v1/customers
Content-Type: application/json

{
  "name": "Manuel",
  "lastName": "Pablo",
  "phone": "244523342",
  "userId": 4
}

###

POST http://localhost:3000/api/v1/customers
Content-Type: application/json

{
  "name": "Melissa",
  "lastName": "Sandoval",
  "phone": "244523342",
  "user": {
    "email": "meli@mail.com",
    "password": "anotheruser2"
  }
}

###

POST http://localhost:3000/api/v1/categories
Content-Type: application/json

{
  "name": "Category 1",
  "image": "http://placeimg.com/640/480"
}

###

POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
  "customerId": 2
}


###

GET http://localhost:3000/api/v1/orders/1

###

POST http://localhost:3000/api/v1/orders/add-item
Content-Type: application/json

{
  "orderId": 1,
  "productId": 1,
  "amount": 7
}
