
# GET http://localhost:3000/api/v1/users


# GET http://localhost:3000/api/v1/products

# POST http://localhost:3000/api/v1/users
# Content-Type: application/json

# {
#   "email": "Fernando33@gt.com",
#   "password": "papapapapapa",
#   "role": "owner"
# }


# GET http://localhost:3000/api/v1/users/4

# PATCH http://localhost:3000/api/v1/users/4
# Content-Type: application/json

# {
#   "email": "andrea2@alison.com"
# }


# DELETE http://localhost:3000/api/v1/users/1

# POST http://localhost:3000/api/v1/customers
# Content-Type: application/json

# {
#   "name": "Jose",
#   "lastName": "Joseeee",
#   "phone": "dsafadsf",
#   "userId": 2
# }
